// Darwin Core Terms - kompletna baza terminów GBIF
export interface DwCTerm {
  type: string;
  required?: boolean;
  unique?: boolean;
  description: string;
  descriptionEN?: string;
  descriptionDE?: string;
  descriptionFR?: string;
  example: string;
  category: string;
  range?: [number, number];
  format?: string;
  allowedValues?: string[];
  defaultValue?: string;
  habitatTranslations?: Record<string, string>;
}

export const dwcTerms: Record<string, DwCTerm> = {
  // Core ID Terms
  eventID: {
    type: "coreID",
    required: true,
    unique: true,
    description: "Unikalny identyfikator zdarzenia zbierania danych",
    descriptionEN: "Unique identifier for the sampling event",
    descriptionDE: "Eindeutiger Bezeichner für das Erfassungsereignis",
    descriptionFR: "Un identifiant pour l'événement d'échantillonnage",
    example: "NHC-00001",
    category: "core",
  },
  occurrenceID: {
    type: "coreID",
    required: true,
    unique: true,
    description: "Unikalny identyfikator obserwacji/okazu",
    descriptionEN: "Unique identifier for the occurrence record",
    descriptionDE: "Eindeutiger Bezeichner für den Vorkommensdatensatz",
    descriptionFR: "Un identifiant pour l'enregistrement d'occurrence",
    example: "urn:catalog:AMUNATCOLL:Mammals:12345",
    category: "core",
  },
  taxonID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator taksonu (linkuje do taxon.txt)",
    descriptionEN: "Identifier linking to taxon extension",
    descriptionDE: "Bezeichner zur Verknüpfung mit der Taxon-Erweiterung",
    descriptionFR: "Un identifiant pour l'ensemble d'informations taxonomiques",
    example: "urn:lsid:catalogueoflife.org:taxon:d79c11aa",
    category: "extension",
  },

  // Location Terms
  decimalLatitude: {
    type: "coordinate",
    required: true,
    range: [-90, 90],
    format: "decimal",
    description: "Szerokość geograficzna w stopniach dziesiętnych",
    descriptionEN: "Geographic latitude in decimal degrees",
    descriptionDE: "Geographische Breite in Dezimalgrad",
    descriptionFR: "La latitude géographique en degrés décimaux du centre géographique d'un lieu",
    example: "52.31611111",
    category: "location",
  },
  decimalLongitude: {
    type: "coordinate",
    required: true,
    range: [-180, 180],
    format: "decimal",
    description: "Długość geograficzna w stopniach dziesiętnych",
    descriptionEN: "Geographic longitude in decimal degrees",
    descriptionDE: "Geographische Länge in Dezimalgrad",
    descriptionFR: "La longitude géographique en degrés décimaux du centre géographique d'un lieu",
    example: "23.05388888",
    category: "location",
  },
  geodeticDatum: {
    type: "controlled",
    required: true,
    allowedValues: ["WGS84", "EPSG:4326", "NAD83", "NAD27"],
    defaultValue: "WGS84",
    description: "Układ odniesienia współrzędnych (zawsze WGS84 dla GBIF)",
    descriptionEN: "Geodetic datum for coordinates (always WGS84 for GBIF)",
    descriptionDE: "Geodätisches Datum für Koordinaten (immer WGS84 für GBIF)",
    descriptionFR: "Le référentiel géodésique sur lequel sont basées les coordonnées géographiques",
    example: "WGS84",
    category: "location",
  },
  countryCode: {
    type: "controlled",
    required: true,
    format: "iso2-country",
    description: "Kod kraju ISO 3166-1 alpha-2",
    descriptionEN: "ISO 3166-1 alpha-2 country code",
    descriptionDE: "ISO 3166-1 Alpha-2-Ländercode",
    descriptionFR: "Le code standard du pays dans lequel le lieu se trouve (ISO 3166-1 alpha-2)",
    example: "PL",
    category: "location",
  },
  coordinateUncertaintyInMeters: {
    type: "decimal",
    required: false,
    range: [0, 10000000],
    description: "Niepewność współrzędnych w metrach (dla UTM/ATPOL typowo 500-1000m)",
    descriptionEN: "Uncertainty of coordinates in meters",
    descriptionDE: "Unsicherheit der Koordinaten in Metern",
    descriptionFR: "La distance horizontale par rapport aux coordonnées décimales données, décrivant le plus petit cercle contenant l'ensemble du lieu",
    example: "500",
    category: "location",
  },
  georeferenceRemarks: {
    type: "text",
    required: false,
    description: "Uwagi do georeferencji - tutaj wpisz ATPOL/UTM",
    descriptionEN: "Notes about georeferencing, including ATPOL/UTM grid references",
    descriptionDE: "Anmerkungen zur Georeferenzierung, einschließlich ATPOL/UTM-Gitterreferenzen",
    descriptionFR: "Notes ou commentaires sur la détermination des coordonnées géographiques",
    example: "System AtPol: FC39 | PL-UTM: GD00",
    category: "location",
  },
  locality: {
    type: "text",
    required: false,
    description: "Nazwa miejscowości lub lokalizacji",
    descriptionEN: "Specific locality name",
    descriptionDE: "Spezifischer Ortsname",
    descriptionFR: "La description spécifique du lieu",
    example: "Białowieża Forest, near Hajnówka",
    category: "location",
  },
  verbatimLocality: {
    type: "text",
    required: false,
    description: "Oryginalna lokalizacja w formacie tekstowym",
    descriptionEN: "Original locality description",
    descriptionDE: "Ursprüngliche Ortsbeschreibung",
    descriptionFR: "La description originale du lieu",
    example: "Dębina municipal forest in Poznań, Poland",
    category: "location",
  },

  // Event Terms
  eventDate: {
    type: "date",
    required: true,
    format: "iso-date",
    description: "Data zdarzenia w formacie ISO 8601",
    descriptionEN: "Date of the event in ISO 8601 format",
    descriptionDE: "Datum des Ereignisses im ISO 8601-Format",
    descriptionFR: "La date ou l'intervalle de dates pendant lequel un événement s'est produit (ISO 8601)",
    example: "2025-01-15",
    category: "event",
  },
  parentEventID: {
    type: "foreignKey",
    required: false,
    description: "ID zdarzenia nadrzędnego (np. ekspedycji)",
    descriptionEN: "Identifier for parent event (e.g., expedition)",
    descriptionDE: "Bezeichner für das übergeordnete Ereignis (z. B. Expedition)",
    descriptionFR: "Un identifiant pour l'événement parent (p. ex. expédition)",
    example: "CB-1974/130",
    category: "event",
  },
  habitat: {
    type: "text",
    required: false,
    description: "Typ siedliska (łąki, lasy, bagna)",
    descriptionEN: "Habitat type description",
    descriptionDE: "Beschreibung des Habitattyps",
    descriptionFR: "Une catégorie ou une description de l'habitat dans lequel l'événement s'est produit",
    example: "Łąki | Olszyny",
    habitatTranslations: {
      Łąki: "Meadows",
      Olszyny: "Alder forests",
      Bagna: "Wetlands",
      "Lasy iglaste": "Coniferous forests",
      "Lasy liściaste": "Deciduous forests",
      Torfowiska: "Peatlands",
      Wydmy: "Sand dunes",
      "Brzegi rzek": "River banks",
    },
    category: "event",
  },
  samplingProtocol: {
    type: "text",
    required: false,
    description: "Metoda zbierania danych",
    descriptionEN: "Sampling methodology used",
    descriptionDE: "Verwendete Erfassungsmethode",
    descriptionFR: "Les noms, références ou descriptions des méthodes d'échantillonnage utilisées",
    example: "UV light trap",
    category: "event",
  },
  recordedBy: {
    type: "text",
    required: false,
    description: "Osoby zbierające dane",
    descriptionEN: "Person(s) who recorded the occurrence",
    descriptionDE: "Person(en), die das Vorkommen erfasst haben",
    descriptionFR: "Une liste de noms de personnes ou de groupes responsables de l'enregistrement de l'occurrence",
    example: "K. Słupecka",
    category: "event",
  },
  organismQuantity: {
    type: "integer",
    required: false,
    range: [0, 1000000],
    description: "Liczba organizmów",
    descriptionEN: "Quantity of organisms",
    descriptionDE: "Anzahl der Organismen",
    descriptionFR: "Un nombre ou une valeur d'énumération pour la quantité d'organismes",
    example: "1",
    category: "occurrence",
  },
  organismQuantityType: {
    type: "text",
    required: false,
    description: "Typ jednostki (np. individual)",
    descriptionEN: "Type of quantity unit",
    descriptionDE: "Art der Mengeneinheit",
    descriptionFR: "Le type de système de quantification utilisé pour la quantité d'organismes",
    example: "individual",
    category: "occurrence",
  },

  // Taxon Terms
  scientificName: {
    type: "text",
    required: true,
    description: "Pełna nazwa naukowa z autorem",
    descriptionEN: "Full scientific name with authorship",
    descriptionDE: "Vollständiger wissenschaftlicher Name mit Autorenschaft",
    descriptionFR: "Le nom scientifique complet, avec les informations d'auteur et de date si connues",
    example: "Quercus robur L.",
    category: "taxon",
  },
  kingdom: {
    type: "controlled",
    required: false,
    allowedValues: ["Animalia", "Plantae", "Fungi", "Bacteria", "Archaea", "Protozoa", "Chromista"],
    description: "Królestwo taksonomiczne",
    descriptionEN: "Taxonomic kingdom",
    descriptionDE: "Taxonomisches Reich",
    descriptionFR: "Le nom scientifique complet du règne auquel le taxon appartient",
    example: "Plantae",
    category: "taxon",
  },

  // Occurrence Terms
  basisOfRecord: {
    type: "controlled",
    required: true,
    allowedValues: [
      "PreservedSpecimen",
      "HumanObservation",
      "MachineObservation",
      "LivingSpecimen",
      "FossilSpecimen",
      "MaterialSample",
    ],
    description: "Podstawa rekordu - typ dowodu",
    descriptionEN: "Basis of the occurrence record",
    descriptionDE: "Grundlage des Vorkommensdatensatzes",
    descriptionFR: "La nature précise de l'enregistrement",
    example: "PreservedSpecimen",
    category: "occurrence",
  },
  individualCount: {
    type: "integer",
    required: false,
    range: [0, 1000000],
    description: "Liczba osobników",
    descriptionEN: "Number of individuals",
    descriptionDE: "Anzahl der Individuen",
    descriptionFR: "Le nombre d'individus présents au moment de l'occurrence",
    example: "5",
    category: "occurrence",
  },

  // Multimedia Terms
  associatedMedia: {
    type: "uri",
    required: false,
    description: "URL do zdjęć/filmów",
    descriptionEN: "URL to associated media files",
    descriptionDE: "URL zu verknüpften Mediendateien",
    descriptionFR: "Une liste d'identifiants de médias associés à l'occurrence",
    example: "https://example.org/image.jpg",
    category: "multimedia",
  },
  // Agent Terms
  agentID: {
    type: "coreID",
    required: true,
    unique: true,
    description: "Unikalny identyfikator agenta (osoby lub organizacji)",
    descriptionEN: "Unique identifier for the agent (person or organization)",
    descriptionDE: "Eindeutiger Bezeichner für den Agenten (Person oder Organisation)",
    descriptionFR: "Un identifiant unique pour l'agent (personne ou organisation)",
    example: "https://orcid.org/0000-0001-2345-6789",
    category: "agent",
  },
  agentType: {
    type: "controlled",
    required: false,
    allowedValues: ["person", "group", "organization", "camera"],
    description: "Kategoria agenta",
    descriptionEN: "A category that best matches the nature of an agent",
    descriptionDE: "Kategorie des Agenten",
    descriptionFR: "Le type d'agent",
    example: "person",
    category: "agent",
  },
  preferredAgentName: {
    type: "text",
    required: false,
    description: "Preferowana nazwa agenta",
    descriptionEN: "Preferred name of the agent",
    descriptionDE: "Bevorzugter Name des Agenten",
    descriptionFR: "Le nom préféré de l'agent",
    example: "Jan Kowalski",
    category: "agent",
  },
  agentRemarks: {
    type: "text",
    required: false,
    description: "Komentarze lub notatki o agencie",
    descriptionEN: "Comments or notes about the agent",
    descriptionDE: "Kommentare oder Anmerkungen zum Agenten",
    descriptionFR: "Commentaires ou notes sur l'agent",
    example: "",
    category: "agent",
  },

  // Agent Agent Role Terms
  relatedAgentID: {
    type: "foreignKey",
    required: true,
    description: "Identyfikator powiązanego agenta",
    descriptionEN: "Identifier for a related agent",
    descriptionDE: "Bezeichner für einen verwandten Agenten",
    descriptionFR: "Identifiant d'un agent lié",
    example: "",
    category: "agent",
  },
  agentRole: {
    type: "text",
    required: false,
    description: "Kategoria roli agenta",
    descriptionEN: "A category that best matches the nature of a role of an agent",
    descriptionDE: "Rolle des Agenten",
    descriptionFR: "Le rôle de l'agent",
    example: "collector",
    category: "agent",
  },
  agentRoleIRI: {
    type: "uri",
    required: false,
    description: "IRI wartości słownika kontrolowanego dla roli agenta",
    descriptionEN: "IRI of the controlled vocabulary value for the agent role",
    descriptionDE: "IRI des kontrollierten Vokabularwerts für die Agentenrolle",
    descriptionFR: "IRI de la valeur du vocabulaire contrôlé pour le rôle de l'agent",
    example: "",
    category: "agent",
  },
  agentRoleSource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego dla roli agenta",
    descriptionEN: "Reference to a controlled vocabulary for the agent role",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für die Agentenrolle",
    descriptionFR: "Référence au vocabulaire contrôlé pour le rôle de l'agent",
    example: "",
    category: "agent",
  },
  agentRoleOrder: {
    type: "integer",
    required: false,
    description: "Pozycja numeryczna roli agenta w zbiorze ról",
    descriptionEN: "Numerical position of an AgentRole in a set of AgentRoles",
    descriptionDE: "Numerische Position einer Agentenrolle in einer Menge von Agentenrollen",
    descriptionFR: "Position numérique d'un rôle d'agent dans un ensemble de rôles d'agent",
    example: "1",
    category: "agent",
  },
  agentRoleDate: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Okres, w którym rola agenta obowiązywała",
    descriptionEN: "Interval during which an AgentRole was in effect",
    descriptionDE: "Zeitraum, in dem die Agentenrolle gültig war",
    descriptionFR: "Intervalle pendant lequel un rôle d'agent était en vigueur",
    example: "2025-01-15",
    category: "agent",
  },

  // Agent Identifier Terms
  identifier: {
    type: "text",
    required: true,
    description: "Jednoznaczne odniesienie do zasobu",
    descriptionEN: "An unambiguous reference to a resource within a given context",
    descriptionDE: "Eine eindeutige Referenz auf eine Ressource",
    descriptionFR: "Une référence non ambiguë à une ressource dans un contexte donné",
    example: "https://orcid.org/0000-0002-1825-0097",
    category: "agent",
  },
  identifierType: {
    type: "text",
    required: false,
    description: "Kategoria lub system identyfikatora",
    descriptionEN: "A category or system that best matches the nature of an identifier",
    descriptionDE: "Eine Kategorie oder ein System, das am besten zur Art des Identifiers passt",
    descriptionFR: "Une catégorie ou un système correspondant à la nature d'un identifiant",
    example: "ORCID",
    category: "agent",
  },
  identifierTypeIRI: {
    type: "uri",
    required: false,
    description: "IRI wartości słownika kontrolowanego dla typu identyfikatora",
    descriptionEN: "IRI of a controlled vocabulary value for a type of identifier",
    descriptionDE: "IRI eines kontrollierten Vokabularwerts für einen Identifiertyp",
    descriptionFR: "IRI d'une valeur de vocabulaire contrôlé pour un type d'identifiant",
    example: "",
    category: "agent",
  },
  identifierTypeSource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego dla typu identyfikatora",
    descriptionEN: "Reference to a controlled vocabulary for the identifier type",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für den Identifiertyp",
    descriptionFR: "Référence au vocabulaire contrôlé pour le type d'identifiant",
    example: "",
    category: "agent",
  },
  identifierLanguage: {
    type: "text",
    required: false,
    description: "Język, w którym identyfikator jest przedstawiony",
    descriptionEN: "A language in which an identifier is presented",
    descriptionDE: "Eine Sprache, in der ein Identifier dargestellt wird",
    descriptionFR: "Une langue dans laquelle un identifiant est présenté",
    example: "en",
    category: "agent",
  },

  // Media subject Terms (shared by agent-media, chronometric-age-media)
  subjectCategory: {
    type: "text",
    required: false,
    description: "Kategoria treści zasobu multimedialnego",
    descriptionEN: "A category for the content of a media resource",
    descriptionDE: "Eine Kategorie für den Inhalt einer Medienressource",
    descriptionFR: "Une catégorie pour le contenu d'une ressource multimédia",
    example: "",
    category: "multimedia",
  },
  subjectCategoryIRI: {
    type: "uri",
    required: false,
    description: "IRI wartości słownika kontrolowanego kategorii tematu",
    descriptionEN: "IRI of a controlled vocabulary value for subject category",
    descriptionDE: "IRI eines kontrollierten Vokabularwerts für die Subjektkategorie",
    descriptionFR: "IRI d'une valeur de vocabulaire contrôlé pour la catégorie du sujet",
    example: "",
    category: "multimedia",
  },
  subjectCategorySource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego kategorii tematu",
    descriptionEN: "Reference to a controlled vocabulary for subject category",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für die Subjektkategorie",
    descriptionFR: "Référence au vocabulaire contrôlé pour la catégorie du sujet",
    example: "",
    category: "multimedia",
  },
  subjectPartLiteral: {
    type: "text",
    required: false,
    description: "Część organizmu pokazana w zasobie multimedialnym (wartość tekstowa)",
    descriptionEN: "Part of organism shown in media resource (literal value)",
    descriptionDE: "Teil des Organismus, der in der Medienressource gezeigt wird (Textwert)",
    descriptionFR: "Partie de l'organisme montrée dans la ressource multimédia (valeur littérale)",
    example: "",
    category: "multimedia",
  },
  subjectPart: {
    type: "uri",
    required: false,
    description: "Część organizmu pokazana w zasobie multimedialnym (IRI)",
    descriptionEN: "Part of organism shown in media resource (IRI)",
    descriptionDE: "Teil des Organismus, der in der Medienressource gezeigt wird (IRI)",
    descriptionFR: "Partie de l'organisme montrée dans la ressource multimédia (IRI)",
    example: "",
    category: "multimedia",
  },
  subjectOrientationLiteral: {
    type: "text",
    required: false,
    description: "Orientacja obiektu w zasobie multimedialnym (wartość tekstowa)",
    descriptionEN: "Orientation of subject in media resource (literal value)",
    descriptionDE: "Orientierung des Objekts in der Medienressource (Textwert)",
    descriptionFR: "Orientation du sujet dans la ressource multimédia (valeur littérale)",
    example: "",
    category: "multimedia",
  },
  subjectOrientation: {
    type: "uri",
    required: false,
    description: "Orientacja obiektu w zasobie multimedialnym (IRI)",
    descriptionEN: "Orientation of subject in media resource (IRI)",
    descriptionDE: "Orientierung des Objekts in der Medienressource (IRI)",
    descriptionFR: "Orientation du sujet dans la ressource multimédia (IRI)",
    example: "",
    category: "multimedia",
  },
  physicalSetting: {
    type: "text",
    required: false,
    description: "Ustawienie treści w zasobie multimedialnym (naturalne, sztuczne, edytowane)",
    descriptionEN: "Physical setting of the content in a media resource",
    descriptionDE: "Physische Umgebung des Inhalts in einer Medienressource",
    descriptionFR: "Le cadre physique du contenu dans une ressource multimédia",
    example: "Natural",
    category: "multimedia",
  },

  // Bibliographic Resource Terms
  referenceID: {
    type: "coreID",
    required: true,
    unique: true,
    description: "Identyfikator zasobu bibliograficznego",
    descriptionEN: "Identifier for a bibliographic resource",
    descriptionDE: "Bezeichner für eine bibliographische Ressource",
    descriptionFR: "Identifiant d'une ressource bibliographique",
    example: "",
    category: "reference",
  },
  parentReferenceID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator nadrzędnego zasobu bibliograficznego",
    descriptionEN: "Identifier for a parent bibliographic resource",
    descriptionDE: "Bezeichner für eine übergeordnete bibliographische Ressource",
    descriptionFR: "Identifiant de la ressource bibliographique parente",
    example: "",
    category: "reference",
  },
  referenceType: {
    type: "text",
    required: false,
    description: "Kategoria zasobu bibliograficznego",
    descriptionEN: "A category for the bibliographic resource",
    descriptionDE: "Eine Kategorie für die bibliographische Ressource",
    descriptionFR: "Une catégorie pour la ressource bibliographique",
    example: "journal article",
    category: "reference",
  },
  bibliographicCitation: {
    type: "text",
    required: false,
    description: "Odniesienie bibliograficzne",
    descriptionEN: "A bibliographic reference for a resource",
    descriptionDE: "Ein bibliographischer Verweis auf eine Ressource",
    descriptionFR: "Une référence bibliographique pour une ressource",
    example: "",
    category: "reference",
  },
  title: {
    type: "text",
    required: false,
    description: "Nazwa nadana zasobowi",
    descriptionEN: "A name given to a resource",
    descriptionDE: "Ein Name für eine Ressource",
    descriptionFR: "Un nom donné à la ressource",
    example: "",
    category: "reference",
  },
  author: {
    type: "text",
    required: false,
    description: "Imię i nazwisko autora",
    descriptionEN: "Name of the author",
    descriptionDE: "Name des Autors",
    descriptionFR: "Nom de l'auteur",
    example: "",
    category: "reference",
  },
  authorID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator autora (agenta)",
    descriptionEN: "Identifier for the author agent",
    descriptionDE: "Bezeichner für den Autor-Agenten",
    descriptionFR: "Identifiant de l'agent auteur",
    example: "",
    category: "reference",
  },
  editor: {
    type: "text",
    required: false,
    description: "Imię i nazwisko redaktora",
    descriptionEN: "Name of the editor",
    descriptionDE: "Name des Herausgebers",
    descriptionFR: "Nom de l'éditeur",
    example: "",
    category: "reference",
  },
  editorID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator redaktora (agenta)",
    descriptionEN: "Identifier for the editor agent",
    descriptionDE: "Bezeichner für den Herausgeber-Agenten",
    descriptionFR: "Identifiant de l'agent éditeur",
    example: "",
    category: "reference",
  },
  publisher: {
    type: "text",
    required: false,
    description: "Nazwa wydawcy",
    descriptionEN: "Name of the publisher",
    descriptionDE: "Name des Verlags",
    descriptionFR: "Nom de l'éditeur (publication)",
    example: "",
    category: "reference",
  },
  publisherID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator wydawcy (agenta)",
    descriptionEN: "Identifier for the publisher agent",
    descriptionDE: "Bezeichner für den Verlags-Agenten",
    descriptionFR: "Identifiant de l'agent éditeur (publication)",
    example: "",
    category: "reference",
  },
  volume: {
    type: "text",
    required: false,
    description: "Numer tomu",
    descriptionEN: "Volume number",
    descriptionDE: "Bandnummer",
    descriptionFR: "Numéro de volume",
    example: "",
    category: "reference",
  },
  issue: {
    type: "text",
    required: false,
    description: "Numer wydania",
    descriptionEN: "Issue number",
    descriptionDE: "Ausgabenummer",
    descriptionFR: "Numéro de parution",
    example: "",
    category: "reference",
  },
  edition: {
    type: "text",
    required: false,
    description: "Wydanie",
    descriptionEN: "Edition of the resource",
    descriptionDE: "Ausgabe der Ressource",
    descriptionFR: "Édition de la ressource",
    example: "",
    category: "reference",
  },
  pages: {
    type: "text",
    required: false,
    description: "Zakres stron",
    descriptionEN: "Page range",
    descriptionDE: "Seitenbereich",
    descriptionFR: "Plage de pages",
    example: "23-25, 34",
    category: "reference",
  },
  version: {
    type: "text",
    required: false,
    description: "Numer wersji",
    descriptionEN: "Version number",
    descriptionDE: "Versionsnummer",
    descriptionFR: "Numéro de version",
    example: "1.5",
    category: "reference",
  },
  issued: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Data formalnego wydania",
    descriptionEN: "Date of formal issuance",
    descriptionDE: "Datum der formalen Veröffentlichung",
    descriptionFR: "Date de publication formelle",
    example: "2025-01-15",
    category: "reference",
  },
  accessed: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Data dostępu do źródła",
    descriptionEN: "Date the source was accessed",
    descriptionDE: "Datum des Zugriffs auf die Quelle",
    descriptionFR: "Date d'accès à la source",
    example: "2025-03-10",
    category: "reference",
  },
  peerReviewStatus: {
    type: "controlled",
    required: false,
    allowedValues: ["true", "false"],
    description: "Czy zasób był recenzowany",
    descriptionEN: "Whether the resource was peer reviewed",
    descriptionDE: "Ob die Ressource peer-reviewed wurde",
    descriptionFR: "Si la ressource a été évaluée par des pairs",
    example: "true",
    category: "reference",
  },
  referenceRemarks: {
    type: "text",
    required: false,
    description: "Komentarze lub notatki o zasobie bibliograficznym",
    descriptionEN: "Comments or notes about the bibliographic resource",
    descriptionDE: "Kommentare oder Anmerkungen zur bibliographischen Ressource",
    descriptionFR: "Commentaires ou notes sur la ressource bibliographique",
    example: "",
    category: "reference",
  },

  // Chronometric Age Terms
  chronometricAgeID: {
    type: "coreID",
    required: true,
    unique: true,
    description: "Identyfikator wieku chronometrycznego",
    descriptionEN: "Identifier for a chronometric age",
    descriptionDE: "Bezeichner für ein chronometrisches Alter",
    descriptionFR: "Identifiant d'un âge chronométrique",
    example: "https://www.canadianarchaeology.ca/samples/70673",
    category: "chronometric",
  },
  verbatimChronometricAge: {
    type: "text",
    required: false,
    description: "Wiek chronometryczny w formie oryginalnej",
    descriptionEN: "Verbatim chronometric age as reported",
    descriptionDE: "Chronometrisches Alter in wörtlicher Form",
    descriptionFR: "Âge chronométrique tel que rapporté",
    example: "",
    category: "chronometric",
  },
  chronometricAgeProtocol: {
    type: "text",
    required: false,
    description: "Opis lub referencja do protokołu datowania",
    descriptionEN: "Description of or reference to a protocol used to determine the age",
    descriptionDE: "Beschreibung oder Referenz eines Protokolls zur Altersbestimmung",
    descriptionFR: "Description ou référence d'un protocole utilisé pour déterminer l'âge",
    example: "",
    category: "chronometric",
  },
  chronometricAgeProtocolID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator protokołu datowania",
    descriptionEN: "Identifier for the dating protocol",
    descriptionDE: "Bezeichner für das Datierungsprotokoll",
    descriptionFR: "Identifiant du protocole de datation",
    example: "",
    category: "chronometric",
  },
  uncalibratedChronometricAge: {
    type: "text",
    required: false,
    description: "Wynik datowania przed kalibracją",
    descriptionEN: "Output of a dating assay before calibration",
    descriptionDE: "Ergebnis einer Datierung vor der Kalibrierung",
    descriptionFR: "Résultat d'un essai de datation avant calibration",
    example: "",
    category: "chronometric",
  },
  chronometricAgeConversionProtocol: {
    type: "text",
    required: false,
    description: "Protokół konwersji nieskalibrowanego wieku",
    descriptionEN: "Protocol used to convert an uncalibrated age",
    descriptionDE: "Protokoll zur Konvertierung eines unkalibrierten Alters",
    descriptionFR: "Protocole utilisé pour convertir un âge non calibré",
    example: "",
    category: "chronometric",
  },
  chronometricAgeConversionProtocolID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator protokołu konwersji",
    descriptionEN: "Identifier for the conversion protocol",
    descriptionDE: "Bezeichner für das Konvertierungsprotokoll",
    descriptionFR: "Identifiant du protocole de conversion",
    example: "",
    category: "chronometric",
  },
  earliestChronometricAge: {
    type: "text",
    required: false,
    description: "Najstarszy możliwy wiek",
    descriptionEN: "Maximum/earliest/oldest possible age",
    descriptionDE: "Maximales/frühestes/ältestes mögliches Alter",
    descriptionFR: "Âge maximum/le plus ancien possible",
    example: "",
    category: "chronometric",
  },
  earliestChronometricAgeReferenceSystem: {
    type: "text",
    required: false,
    description: "System referencyjny najstarszego wieku",
    descriptionEN: "Reference system for the earliest chronometric age",
    descriptionDE: "Referenzsystem für das früheste chronometrische Alter",
    descriptionFR: "Système de référence pour l'âge chronométrique le plus ancien",
    example: "",
    category: "chronometric",
  },
  latestChronometricAge: {
    type: "text",
    required: false,
    description: "Najmłodszy możliwy wiek",
    descriptionEN: "Minimum/latest/youngest possible age",
    descriptionDE: "Minimales/jüngstes mögliches Alter",
    descriptionFR: "Âge minimum/le plus récent possible",
    example: "",
    category: "chronometric",
  },
  latestChronometricAgeReferenceSystem: {
    type: "text",
    required: false,
    description: "System referencyjny najmłodszego wieku",
    descriptionEN: "Reference system for the latest chronometric age",
    descriptionDE: "Referenzsystem für das jüngste chronometrische Alter",
    descriptionFR: "Système de référence pour l'âge chronométrique le plus récent",
    example: "",
    category: "chronometric",
  },
  chronometricAgeUncertaintyInYears: {
    type: "integer",
    required: false,
    description: "Niepewność czasowa w latach",
    descriptionEN: "Temporal uncertainty in years",
    descriptionDE: "Zeitliche Unsicherheit in Jahren",
    descriptionFR: "Incertitude temporelle en années",
    example: "",
    category: "chronometric",
  },
  chronometricAgeUncertaintyMethod: {
    type: "text",
    required: false,
    description: "Metoda określenia niepewności",
    descriptionEN: "Method used to generate the uncertainty value",
    descriptionDE: "Methode zur Bestimmung der Unsicherheit",
    descriptionFR: "Méthode utilisée pour générer la valeur d'incertitude",
    example: "",
    category: "chronometric",
  },
  materialDated: {
    type: "text",
    required: false,
    description: "Opis datowanego materiału",
    descriptionEN: "Description of the material that was dated",
    descriptionDE: "Beschreibung des datierten Materials",
    descriptionFR: "Description du matériau daté",
    example: "",
    category: "chronometric",
  },
  materialDatedID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator datowanego materiału",
    descriptionEN: "Identifier for the material that was dated",
    descriptionDE: "Bezeichner für das datierte Material",
    descriptionFR: "Identifiant du matériau daté",
    example: "",
    category: "chronometric",
  },
  materialDatedRelationship: {
    type: "text",
    required: false,
    description: "Relacja datowanego materiału do okazu",
    descriptionEN: "Relationship of dated material to the specimen",
    descriptionDE: "Beziehung des datierten Materials zum Exemplar",
    descriptionFR: "Relation du matériau daté au spécimen",
    example: "",
    category: "chronometric",
  },
  chronometricAgeDeterminedBy: {
    type: "text",
    required: false,
    description: "Osoby odpowiedzialne za datowanie",
    descriptionEN: "Agents responsible for determining the age",
    descriptionDE: "Verantwortliche für die Altersbestimmung",
    descriptionFR: "Agents responsables de la détermination de l'âge",
    example: "",
    category: "chronometric",
  },
  chronometricAgeDeterminedByID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator agenta odpowiedzialnego za datowanie",
    descriptionEN: "Identifier for the agent who determined the age",
    descriptionDE: "Bezeichner für den Agenten, der das Alter bestimmt hat",
    descriptionFR: "Identifiant de l'agent ayant déterminé l'âge",
    example: "",
    category: "chronometric",
  },
  chronometricAgeDeterminedDate: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Data określenia wieku",
    descriptionEN: "Date on which the age was determined",
    descriptionDE: "Datum der Altersbestimmung",
    descriptionFR: "Date de détermination de l'âge",
    example: "2025-01-15",
    category: "chronometric",
  },
  chronometricAgeReferences: {
    type: "text",
    required: false,
    description: "Lista zasobów bibliograficznych powiązanych z wiekiem",
    descriptionEN: "Bibliographic resources associated with the age",
    descriptionDE: "Bibliographische Ressourcen zum Alter",
    descriptionFR: "Ressources bibliographiques associées à l'âge",
    example: "",
    category: "chronometric",
  },
  chronometricAgeRemarks: {
    type: "text",
    required: false,
    description: "Komentarze lub notatki o wieku chronometrycznym",
    descriptionEN: "Comments or notes about the chronometric age",
    descriptionDE: "Kommentare oder Anmerkungen zum chronometrischen Alter",
    descriptionFR: "Commentaires ou notes sur l'âge chronométrique",
    example: "",
    category: "chronometric",
  },

  // Chronometric Age Protocol Terms
  protocolID: {
    type: "foreignKey",
    required: true,
    description: "Identyfikator protokołu",
    descriptionEN: "Identifier for a protocol",
    descriptionDE: "Bezeichner für ein Protokoll",
    descriptionFR: "Identifiant d'un protocole",
    example: "",
    category: "chronometric",
  },

  // Assertion Terms (shared by chronometric-age-assertion)
  assertionID: {
    type: "coreID",
    required: false,
    unique: true,
    description: "Identyfikator asercji",
    descriptionEN: "Identifier for an assertion",
    descriptionDE: "Bezeichner für eine Aussage",
    descriptionFR: "Identifiant d'une assertion",
    example: "",
    category: "assertion",
  },
  verbatimAssertionType: {
    type: "text",
    required: false,
    description: "Oryginalny typ asercji",
    descriptionEN: "Verbatim assertion type as it appeared in the original record",
    descriptionDE: "Ursprünglicher Aussagetyp wie im Originaldatensatz",
    descriptionFR: "Type d'assertion tel qu'il apparaît dans l'enregistrement d'origine",
    example: "water_temp",
    category: "assertion",
  },
  assertionType: {
    type: "text",
    required: false,
    description: "Kategoria asercji",
    descriptionEN: "A category that best matches the nature of an assertion",
    descriptionDE: "Eine Kategorie, die am besten zur Art der Aussage passt",
    descriptionFR: "Une catégorie correspondant à la nature d'une assertion",
    example: "tail length",
    category: "assertion",
  },
  assertionTypeIRI: {
    type: "uri",
    required: false,
    description: "IRI typu asercji",
    descriptionEN: "IRI of a controlled vocabulary value for the assertion type",
    descriptionDE: "IRI eines kontrollierten Vokabularwerts für den Aussagetyp",
    descriptionFR: "IRI d'une valeur de vocabulaire contrôlé pour le type d'assertion",
    example: "",
    category: "assertion",
  },
  assertionTypeSource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego typu asercji",
    descriptionEN: "Reference to a controlled vocabulary for the assertion type",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für den Aussagetyp",
    descriptionFR: "Référence au vocabulaire contrôlé pour le type d'assertion",
    example: "",
    category: "assertion",
  },
  assertionMadeDate: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Data utworzenia asercji",
    descriptionEN: "Date on which the assertion was created",
    descriptionDE: "Datum der Erstellung der Aussage",
    descriptionFR: "Date de création de l'assertion",
    example: "2025-01-15",
    category: "assertion",
  },
  assertionEffectiveDate: {
    type: "date",
    required: false,
    format: "iso-date",
    description: "Data wejścia w życie asercji",
    descriptionEN: "Date on which the assertion was first in effect",
    descriptionDE: "Datum des Inkrafttretens der Aussage",
    descriptionFR: "Date d'entrée en vigueur de l'assertion",
    example: "2025-01-15",
    category: "assertion",
  },
  assertionValue: {
    type: "text",
    required: false,
    description: "Wartość asercji (nieliczbowa)",
    descriptionEN: "Asserted value, if not numeric",
    descriptionDE: "Aussagewert, falls nicht numerisch",
    descriptionFR: "Valeur assertée, si non numérique",
    example: "",
    category: "assertion",
  },
  assertionValueIRI: {
    type: "uri",
    required: false,
    description: "IRI wartości asercji",
    descriptionEN: "IRI of the controlled vocabulary value for the assertion value",
    descriptionDE: "IRI des kontrollierten Vokabularwerts für den Aussagewert",
    descriptionFR: "IRI de la valeur du vocabulaire contrôlé pour la valeur de l'assertion",
    example: "",
    category: "assertion",
  },
  assertionValueSource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego wartości asercji",
    descriptionEN: "Reference to a controlled vocabulary for the assertion value",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für den Aussagewert",
    descriptionFR: "Référence au vocabulaire contrôlé pour la valeur de l'assertion",
    example: "",
    category: "assertion",
  },
  assertionValueNumeric: {
    type: "decimal",
    required: false,
    description: "Wartość asercji (liczbowa)",
    descriptionEN: "Asserted value, if numeric",
    descriptionDE: "Aussagewert, falls numerisch",
    descriptionFR: "Valeur assertée, si numérique",
    example: "",
    category: "assertion",
  },
  assertionUnit: {
    type: "text",
    required: false,
    description: "Jednostka wartości asercji",
    descriptionEN: "Unit for the assertion value",
    descriptionDE: "Einheit für den Aussagewert",
    descriptionFR: "Unité pour la valeur de l'assertion",
    example: "m",
    category: "assertion",
  },
  assertionUnitIRI: {
    type: "uri",
    required: false,
    description: "IRI jednostki asercji",
    descriptionEN: "IRI for the assertion unit",
    descriptionDE: "IRI für die Aussageeinheit",
    descriptionFR: "IRI de l'unité d'assertion",
    example: "",
    category: "assertion",
  },
  assertionUnitSource: {
    type: "text",
    required: false,
    description: "Referencja do słownika kontrolowanego jednostki asercji",
    descriptionEN: "Reference to a controlled vocabulary for the assertion unit",
    descriptionDE: "Referenz auf ein kontrolliertes Vokabular für die Aussageeinheit",
    descriptionFR: "Référence au vocabulaire contrôlé pour l'unité d'assertion",
    example: "",
    category: "assertion",
  },
  assertionError: {
    type: "text",
    required: false,
    description: "Opis potencjalnego błędu wartości asercji",
    descriptionEN: "Description of the potential error in the assertion value",
    descriptionDE: "Beschreibung des möglichen Fehlers im Aussagewert",
    descriptionFR: "Description de l'erreur potentielle de la valeur d'assertion",
    example: "0.01",
    category: "assertion",
  },
  assertionBy: {
    type: "text",
    required: false,
    description: "Osoby odpowiedzialne za asercję",
    descriptionEN: "Agents responsible for making the assertion",
    descriptionDE: "Verantwortliche für die Aussage",
    descriptionFR: "Agents responsables de l'assertion",
    example: "",
    category: "assertion",
  },
  assertionByID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator agenta odpowiedzialnego za asercję",
    descriptionEN: "Identifier for the agent who made the assertion",
    descriptionDE: "Bezeichner für den Agenten, der die Aussage gemacht hat",
    descriptionFR: "Identifiant de l'agent ayant fait l'assertion",
    example: "",
    category: "assertion",
  },
  assertionProtocols: {
    type: "text",
    required: false,
    description: "Protokoły użyte do wykonania asercji",
    descriptionEN: "Protocols used in making the assertion",
    descriptionDE: "Protokolle zur Erstellung der Aussage",
    descriptionFR: "Protocoles utilisés pour l'assertion",
    example: "",
    category: "assertion",
  },
  assertionProtocolID: {
    type: "foreignKey",
    required: false,
    description: "Identyfikator protokołu asercji",
    descriptionEN: "Identifier for the assertion protocol",
    descriptionDE: "Bezeichner für das Aussageprotokoll",
    descriptionFR: "Identifiant du protocole d'assertion",
    example: "",
    category: "assertion",
  },
  assertionReferences: {
    type: "text",
    required: false,
    description: "Zasoby bibliograficzne powiązane z asercją",
    descriptionEN: "Bibliographic resources associated with the assertion",
    descriptionDE: "Bibliographische Ressourcen zur Aussage",
    descriptionFR: "Ressources bibliographiques associées à l'assertion",
    example: "",
    category: "assertion",
  },
  assertionRemarks: {
    type: "text",
    required: false,
    description: "Komentarze lub notatki o asercji",
    descriptionEN: "Comments or notes about the assertion",
    descriptionDE: "Kommentare oder Anmerkungen zur Aussage",
    descriptionFR: "Commentaires ou notes sur l'assertion",
    example: "",
    category: "assertion",
  },
export const termCategories: Record<string, { name: Record<string, string>; icon: string; color: string }> = {
  core: { name: { pl: "Core IDs", en: "Core IDs", fr: "IDs principaux", de: "Core-IDs" }, icon: "Key", color: "#22d3ee" },
  location: { name: { pl: "Lokalizacja", en: "Location", fr: "Localisation", de: "Standort" }, icon: "MapPin", color: "#22c55e" },
  event: { name: { pl: "Zdarzenie", en: "Event", fr: "Événement", de: "Ereignis" }, icon: "Calendar", color: "#a855f7" },
  taxon: { name: { pl: "Takson", en: "Taxon", fr: "Taxon", de: "Taxon" }, icon: "Leaf", color: "#f59e0b" },
  occurrence: { name: { pl: "Obserwacja", en: "Occurrence", fr: "Occurrence", de: "Vorkommen" }, icon: "Eye", color: "#3b82f6" },
  multimedia: { name: { pl: "Multimedia", en: "Multimedia", fr: "Multimédia", de: "Multimedia" }, icon: "Image", color: "#ec4899" },
  extension: { name: { pl: "Rozszerzenia", en: "Extensions", fr: "Extensions", de: "Erweiterungen" }, icon: "Link", color: "#6366f1" },
  agent: { name: { pl: "Agent", en: "Agent", fr: "Agent", de: "Agent" }, icon: "Users", color: "#14b8a6" },
};

// Reguły walidacji GBIF
export const validationRules = [
  { field: "eventID", required: true, unique: true, format: null },
  { field: "occurrenceID", required: true, unique: true, format: null },
  { field: "decimalLatitude", required: true, unique: false, format: "decimal", range: [-90, 90] },
  { field: "decimalLongitude", required: true, unique: false, format: "decimal", range: [-180, 180] },
  { field: "geodeticDatum", required: true, unique: false, value: "WGS84" },
  { field: "countryCode", required: true, unique: false, format: "iso2-country" },
  { field: "eventDate", required: true, unique: false, format: "iso-date" },
  { field: "basisOfRecord", required: true, unique: false, format: "controlled" },
  { field: "scientificName", required: true, unique: false, format: null },
];

// Sample data CSV
export const sampleEventsCSV = `Project_Name,Id,Specimen,Author,Collection_date,Quantity,Quantity_unit,Location,Latitude,Longitude,Coordinate_system,Settlement
Invasive species,3431,Acer negundo,K. Słupecka,15-05-2025,1,individual,"Dębina municipal forest in Poznań, Poland",52.369327,16.925402,WGS84,Forest near railroad
Invasive species,6405,Solidago canadensis,M. Kowalski,17-06-2025,5,individual,"Marii Skłodowskiej-Curie Park, Poznań, Poland",52.3935228,16.918701,WGS84,Park`;

// ISO Country Codes (wybrane)
export const isoCodes = [
  "PL",
  "DE",
  "CZ",
  "SK",
  "UA",
  "BY",
  "LT",
  "RU",
  "SE",
  "NO",
  "FI",
  "DK",
  "GB",
  "FR",
  "ES",
  "IT",
  "AT",
  "CH",
  "NL",
  "BE",
  "US",
  "CA",
  "AU",
  "BR",
];

export default dwcTerms;
