/**
 * @file schemaData.ts
 * @description Definicje typów schematów DwC-DP (Darwin Core Data Package) oraz ich pól.
 *
 * Zawiera:
 * - `schemaTypes` — lista wszystkich schematów z ikonami i kolorami
 * - `schemaTerms` — mapowanie schematów na wymagane i opcjonalne pola (termy)
 *
 * Źródło: https://gbif.github.io/dwc-dp/qrg/
 */

import {
  Grid3X3,
  Target,
  Calendar,
  Image,
  Search as SearchIcon,
  FileSpreadsheet,
  FileText,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** Typ opisujący jeden schemat DwC-DP w interfejsie */
export interface SchemaType {
  /** Unikalny identyfikator schematu (np. "event", "occurrence") */
  id: string;
  /** Czytelna nazwa schematu (np. "Event", "Occurrence") */
  name: string;
  /** Ikona lucide-react do wyświetlania przy schemacie */
  icon: LucideIcon;
  /** Klasa tailwind z kolorem tła ikony (np. "bg-purple-600") */
  color: string;
}

/** Typ opisujący pola wymagane i opcjonalne schematu */
export interface SchemaTermDefinition {
  /** Pola wymagane (np. ["eventID"]) */
  required: string[];
  /** Pola opcjonalne */
  optional: string[];
}

/**
 * Wszystkie schematy DwC-DP z metadanymi wizualnymi.
 * Kolejność odpowiada logicznemu grupowaniu: Event → Occurrence → Organism → Material → Media → Identification → Agent → ...
 */
export const schemaTypes: SchemaType[] = [
  { id: "event", name: "Event", icon: Grid3X3, color: "bg-purple-600" },
  { id: "occurrence", name: "Occurrence", icon: Target, color: "bg-rose-600" },
  { id: "occurrence-agent-role", name: "Occurrence Agent Role", icon: Users, color: "bg-rose-500" },
  { id: "occurrence-assertion", name: "Occurrence Assertion", icon: FileText, color: "bg-rose-400" },
  { id: "occurrence-identifier", name: "Occurrence Identifier", icon: FileText, color: "bg-rose-300" },
  { id: "occurrence-media", name: "Occurrence Media", icon: Image, color: "bg-rose-200" },
  { id: "occurrence-protocol", name: "Occurrence Protocol", icon: FileText, color: "bg-rose-100" },
  { id: "occurrence-reference", name: "Occurrence Reference", icon: FileText, color: "bg-pink-600" },
  { id: "organism", name: "Organism", icon: Users, color: "bg-emerald-600" },
  { id: "organism-assertion", name: "Organism Assertion", icon: FileText, color: "bg-emerald-500" },
  { id: "organism-identifier", name: "Organism Identifier", icon: FileText, color: "bg-emerald-400" },
  { id: "organism-interaction", name: "Organism Interaction", icon: Users, color: "bg-emerald-300" },
  { id: "organism-interaction-agent-role", name: "Org. Interaction Agent Role", icon: Users, color: "bg-emerald-200" },
  { id: "organism-interaction-assertion", name: "Org. Interaction Assertion", icon: FileText, color: "bg-emerald-100" },
  { id: "material", name: "Material Entity", icon: Calendar, color: "bg-amber-600" },
  { id: "material-agent-role", name: "Material Agent Role", icon: Users, color: "bg-amber-500" },
  { id: "material-assertion", name: "Material Assertion", icon: FileText, color: "bg-amber-400" },
  { id: "material-identifier", name: "Material Identifier", icon: FileText, color: "bg-amber-300" },
  { id: "material-geological-context", name: "Material Geological Context", icon: Grid3X3, color: "bg-amber-200" },
  { id: "material-media", name: "Material Media", icon: Image, color: "bg-amber-100" },
  { id: "material-protocol", name: "Material Protocol", icon: FileText, color: "bg-yellow-600" },
  { id: "material-provenance", name: "Material Provenance", icon: FileText, color: "bg-yellow-500" },
  { id: "material-reference", name: "Material Reference", icon: FileText, color: "bg-yellow-400" },
  { id: "material-usage-policy", name: "Material Usage Policy", icon: FileText, color: "bg-yellow-300" },
  { id: "media", name: "Media", icon: Image, color: "bg-blue-600" },
  { id: "media-agent-role", name: "Media Agent Role", icon: Users, color: "bg-blue-500" },
  { id: "media-assertion", name: "Media Assertion", icon: FileText, color: "bg-blue-400" },
  { id: "media-identifier", name: "Media Identifier", icon: FileText, color: "bg-blue-300" },
  { id: "media-provenance", name: "Media Provenance", icon: FileText, color: "bg-blue-200" },
  { id: "media-usage-policy", name: "Media Usage Policy", icon: FileText, color: "bg-blue-100" },
  { id: "identification", name: "Identification", icon: SearchIcon, color: "bg-cyan-600" },
  { id: "identification-agent-role", name: "Identification Agent Role", icon: Users, color: "bg-cyan-500" },
  { id: "identification-reference", name: "Identification Reference", icon: FileText, color: "bg-cyan-400" },
  { id: "identification-taxon", name: "Identification Taxon", icon: Target, color: "bg-cyan-300" },
  { id: "agent", name: "Agent", icon: Users, color: "bg-teal-600" },
  { id: "agent-agent-role", name: "Agent Agent Role", icon: Users, color: "bg-teal-500" },
  { id: "agent-identifier", name: "Agent Identifier", icon: Users, color: "bg-teal-400" },
  { id: "agent-media", name: "Agent Media", icon: Image, color: "bg-teal-300" },
  { id: "bibliographic-resource", name: "Bibliographic Resource", icon: FileText, color: "bg-orange-600" },
  { id: "chronometric-age", name: "Chronometric Age", icon: Calendar, color: "bg-indigo-600" },
  { id: "chronometric-age-agent-role", name: "Chrono Age Agent Role", icon: Users, color: "bg-indigo-500" },
  { id: "chronometric-age-assertion", name: "Chrono Age Assertion", icon: FileText, color: "bg-indigo-400" },
  { id: "chronometric-age-media", name: "Chrono Age Media", icon: Image, color: "bg-indigo-300" },
  { id: "chronometric-age-protocol", name: "Chrono Age Protocol", icon: FileText, color: "bg-indigo-200" },
  { id: "chronometric-age-reference", name: "Chrono Age Reference", icon: FileText, color: "bg-indigo-100" },
  { id: "geological-context", name: "Geological Context", icon: Grid3X3, color: "bg-stone-600" },
  { id: "geological-context-media", name: "Geological Context Media", icon: Image, color: "bg-stone-500" },
  { id: "event-agent-role", name: "Event Agent Role", icon: Users, color: "bg-purple-500" },
  { id: "event-assertion", name: "Event Assertion", icon: FileText, color: "bg-purple-400" },
  { id: "event-identifier", name: "Event Identifier", icon: FileText, color: "bg-purple-300" },
  { id: "event-media", name: "Event Media", icon: Image, color: "bg-purple-200" },
  { id: "event-protocol", name: "Event Protocol", icon: FileText, color: "bg-purple-100" },
  { id: "event-provenance", name: "Event Provenance", icon: FileText, color: "bg-violet-500" },
  { id: "event-reference", name: "Event Reference", icon: FileText, color: "bg-violet-400" },
  { id: "molecular-protocol", name: "Molecular Protocol", icon: FileSpreadsheet, color: "bg-lime-600" },
  { id: "molecular-protocol-agent-role", name: "Mol. Protocol Agent Role", icon: Users, color: "bg-lime-500" },
  { id: "molecular-protocol-assertion", name: "Mol. Protocol Assertion", icon: FileText, color: "bg-lime-400" },
  { id: "molecular-protocol-reference", name: "Mol. Protocol Reference", icon: FileText, color: "bg-lime-300" },
  { id: "nucleotide-analysis", name: "Nucleotide Analysis", icon: FileSpreadsheet, color: "bg-green-600" },
  { id: "nucleotide-analysis-assertion", name: "Nucleotide Analysis Assertion", icon: FileText, color: "bg-green-500" },
  { id: "organism-interaction-media", name: "Org. Interaction Media", icon: Image, color: "bg-emerald-50" },
  { id: "organism-interaction-reference", name: "Org. Interaction Reference", icon: FileText, color: "bg-teal-100" },
  { id: "organism-reference", name: "Organism Reference", icon: FileText, color: "bg-teal-50" },
  { id: "organism-relationship", name: "Organism Relationship", icon: Users, color: "bg-cyan-100" },
  { id: "protocol", name: "Protocol", icon: FileText, color: "bg-gray-600" },
  { id: "protocol-reference", name: "Protocol Reference", icon: FileText, color: "bg-gray-500" },
  { id: "provenance", name: "Provenance", icon: FileText, color: "bg-slate-600" },
  { id: "resource-relationship", name: "Resource Relationship", icon: Users, color: "bg-slate-500" },
  { id: "survey", name: "Survey", icon: Target, color: "bg-sky-600" },
  { id: "survey-agent-role", name: "Survey Agent Role", icon: Users, color: "bg-sky-500" },
  { id: "survey-assertion", name: "Survey Assertion", icon: FileText, color: "bg-sky-400" },
  { id: "survey-identifier", name: "Survey Identifier", icon: FileText, color: "bg-sky-300" },
  { id: "survey-protocol", name: "Survey Protocol", icon: FileText, color: "bg-sky-200" },
  { id: "survey-reference", name: "Survey Reference", icon: FileText, color: "bg-sky-100" },
  { id: "survey-target", name: "Survey Target", icon: Target, color: "bg-sky-50" },
  { id: "usage-policy", name: "Usage Policy", icon: FileText, color: "bg-fuchsia-600" },
];

/**
 * Definicje pól (termów) dla każdego schematu DwC-DP.
 * Klucz = ID schematu, wartość = { required, optional }.
 * Źródło: https://gbif.github.io/dwc-dp/qrg/
 */
export const schemaTerms: Record<string, SchemaTermDefinition> = {
  event: {
    required: ["eventID"],
    optional: [
      "parentEventID", "preferredEventName", "eventCategory", "eventType",
      "datasetName", "datasetID", "fieldNumber",
      "eventConductedBy", "eventConductedByID",
      "eventDate", "eventTime", "startDayOfYear", "endDayOfYear",
      "year", "month", "day", "verbatimEventDate",
      "verbatimLocality", "verbatimElevation", "verbatimDepth",
      "verbatimCoordinates", "verbatimLatitude", "verbatimLongitude",
      "verbatimCoordinateSystem", "verbatimSRS",
      "georeferenceVerificationStatus",
      "higherGeography", "higherGeographyID",
      "continent", "waterBody", "islandGroup", "island",
      "country", "countryCode", "stateProvince", "county", "municipality", "locality",
      "siteNumber", "locationID",
      "minimumElevationInMeters", "maximumElevationInMeters", "verticalDatum",
      "minimumDepthInMeters", "maximumDepthInMeters",
      "minimumDistanceAboveSurfaceInMeters", "maximumDistanceAboveSurfaceInMeters",
      "locationRemarks",
      "decimalLatitude", "decimalLongitude", "geodeticDatum",
      "coordinateUncertaintyInMeters", "coordinatePrecision", "pointRadiusSpatialFit",
      "footprintWKT", "footprintSRS", "footprintSpatialFit",
      "georeferencedBy", "georeferencedByID", "georeferencedDate",
      "georeferenceProtocol", "georeferenceProtocolID",
      "georeferenceSources", "georeferenceRemarks",
      "preferredSpatialRepresentation", "geologicalContextID",
      "habitat", "eventEffort", "fieldNotes",
      "eventReferences", "eventRemarks",
      "samplingProtocol", "samplingEffort",
      "sampleSizeValue", "sampleSizeUnit",
      "feedbackURL", "informationWithheld", "dataGeneralizations", "basisOfRecord",
    ],
  },
  occurrence: {
    required: ["occurrenceID", "eventID"],
    optional: [
      "isPartOfOccurrenceID", "surveyTargetID",
      "recordedBy", "recordedByID",
      "organismQuantity", "organismQuantityType",
      "sex", "lifeStage", "reproductiveCondition", "caste",
      "behavior", "vitality",
      "establishmentMeans", "degreeOfEstablishment", "pathway", "substrate",
      "occurrenceStatus", "occurrenceReferences",
      "informationWithheld", "dataGeneralizations", "occurrenceRemarks",
      "organismID", "organismScope", "organismName", "causeOfDeath", "organismRemarks",
      "verbatimIdentification", "identifiedBy", "identifiedByID",
      "dateIdentified", "identificationReferences",
      "identificationVerificationStatus", "identificationRemarks",
      "taxonID", "scientificNameID", "scientificName", "scientificNameAuthorship",
      "vernacularName", "taxonRank", "externalClassificationSource", "feedbackURL",
    ],
  },
  "occurrence-agent-role": {
    required: ["agentID", "occurrenceID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "occurrence-assertion": {
    required: ["occurrenceID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "occurrence-identifier": {
    required: ["occurrenceID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "occurrence-media": {
    required: ["mediaID", "occurrenceID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "occurrence-protocol": {
    required: ["occurrenceID", "protocolID"],
    optional: [],
  },
  "occurrence-reference": {
    required: ["occurrenceID", "referenceID"],
    optional: ["relationshipType"],
  },
  organism: {
    required: ["organismID"],
    optional: ["organismScope", "organismName", "causeOfDeath", "associatedOrganisms", "organismRemarks"],
  },
  "organism-assertion": {
    required: ["organismID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "organism-identifier": {
    required: ["organismID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "organism-interaction": {
    required: ["organismInteractionID", "eventID", "subjectOccurrenceID"],
    optional: [
      "organismInteractionDescription", "subjectOrganismPart",
      "organismInteractionType",
      "relatedOccurrenceID", "externalRelatedOccurrenceID", "externalRelatedOccurrenceSource",
      "relatedOrganismPart", "feedbackURL",
    ],
  },
  "organism-interaction-agent-role": {
    required: ["agentID", "organismInteractionID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "organism-interaction-assertion": {
    required: ["organismInteractionID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  material: {
    required: ["materialEntityID"],
    optional: [
      "digitalSpecimenID", "eventID", "materialCategory", "discipline", "materialEntityType",
      "institutionCode", "institutionID", "ownerInstitutionCode", "ownerInstitutionID",
      "collectionCode", "collectionID", "catalogNumber", "otherCatalogNumbers",
      "collectedBy", "collectedByID",
      "objectQuantity", "objectQuantityType", "collectorNumber",
      "preparations", "disposition", "verbatimLabel",
      "associatedSequences", "materialReferences",
      "informationWithheld", "dataGeneralizations", "materialEntityRemarks",
      "evidenceForOccurrenceID", "derivedFromMaterialEntityID",
      "derivationEventID", "derivationType", "isPartOfMaterialEntityID",
      "verbatimIdentification", "typeStatus", "typeDesignationType", "typifiedName",
      "identifiedBy", "identifiedByID", "dateIdentified",
      "identificationReferences", "identificationVerificationStatus", "identificationRemarks",
      "taxonID", "scientificNameID", "geoClassificationCode", "geoName",
      "scientificName", "scientificNameAuthorship", "vernacularName",
      "taxonRank", "externalClassificationSource", "feedbackURL",
    ],
  },
  "material-agent-role": {
    required: ["agentID", "materialEntityID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "material-assertion": {
    required: ["materialEntityID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "material-identifier": {
    required: ["materialEntityID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "material-geological-context": {
    required: ["materialEntityID", "geologicalContextID"],
    optional: [],
  },
  "material-media": {
    required: ["mediaID", "materialEntityID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "material-protocol": {
    required: ["materialEntityID", "protocolID"],
    optional: [],
  },
  "material-provenance": {
    required: ["provenanceID", "materialEntityID"],
    optional: [],
  },
  "material-reference": {
    required: ["referenceID", "materialEntityID"],
    optional: ["relationshipType"],
  },
  "material-usage-policy": {
    required: ["usagePolicyID", "materialEntityID"],
    optional: [],
  },
  media: {
    required: ["mediaID"],
    optional: [
      "derivedFromMediaID", "isPartOfMediaID",
      "mediaType", "title", "description", "caption",
      "subtypeLiteral", "subtypeIRI",
      "collectionCode", "collectionID",
      "CreateDate", "timeOfDay", "digitizationDate",
      "captureDevice", "frameRate", "resourceCreationTechnique",
      "sample-rate", "modified",
      "language", "languageIRI",
      "MetadataDate", "metadataLanguageLiteral", "metadataLanguageIRI",
      "providerManagedID", "available",
      "hasServiceAccessPoint", "serviceExpectation",
      "accessURI", "format", "formatIRI",
      "variantLiteral", "variantIRI", "variantDescription",
      "PixelXDimension", "PixelYDimension",
      "hashFunction", "hashValue",
      "furtherInformationURL",
      "commenterLiteral", "commenterID", "comments",
      "Rating", "reviewerLiteral", "reviewerID", "reviewerComments",
      "physicalSetting",
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "tag",
      "subjectPartLiteral", "subjectPartIRI",
      "subjectOrientationLiteral", "subjectOrientationIRI",
      "startTime", "endTime", "startTimestamp", "endTimestamp",
      "mediaDuration", "mediaSpeed",
      "freqHigh", "freqLow",
      "xFrac", "yFrac", "heightFrac", "widthFrac", "radius",
    ],
  },
  "media-agent-role": {
    required: ["agentID", "mediaID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "media-assertion": {
    required: ["mediaID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "media-identifier": {
    required: ["mediaID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "media-provenance": {
    required: ["provenanceID", "mediaID"],
    optional: [],
  },
  "media-usage-policy": {
    required: ["usagePolicyID", "mediaID"],
    optional: [],
  },
  identification: {
    required: ["identificationID"],
    optional: [
      "materialEntityID", "mediaID", "nucleotideAnalysisID", "nucleotideSequenceID",
      "occurrenceID", "organismID",
      "verbatimIdentification", "isAcceptedIdentification", "taxonFormula",
      "typeStatus", "typeDesignationType",
      "identifiedBy", "identifiedByID", "dateIdentified",
      "identificationReferences", "taxonAssignmentMethod",
      "identificationVerificationStatus", "identificationRemarks",
      "taxonID", "scientificNameID", "geoClassificationCode", "geoName",
      "scientificName", "scientificNameAuthorship", "vernacularName",
      "taxonRank", "externalClassificationSource",
      "kingdom", "phylum", "class", "order", "family", "subfamily",
      "genus", "genericName", "subgenus", "infragenericEpithet",
      "specificEpithet", "infraspecificEpithet", "cultivarEpithet",
      "nameAccordingTo", "nomenclaturalCode", "nomenclaturalStatus",
      "namePublishedIn", "namePublishedInYear",
      "taxonRemarks", "feedbackURL",
    ],
  },
  "identification-agent-role": {
    required: ["agentID", "identificationID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "identification-reference": {
    required: ["identificationID", "referenceID"],
    optional: ["relationshipType"],
  },
  "identification-taxon": {
    required: ["identificationID"],
    optional: [
      "taxonSortOrder", "taxonID", "scientificNameID",
      "geoClassificationCode", "geoName",
      "scientificName", "scientificNameAuthorship", "vernacularName",
      "taxonRank", "externalClassificationSource",
      "kingdom", "phylum", "class", "order", "family", "subfamily",
      "genus", "genericName", "subgenus", "infragenericEpithet",
      "specificEpithet", "infraspecificEpithet", "cultivarEpithet",
      "nameAccordingTo", "nomenclaturalCode", "nomenclaturalStatus",
      "namePublishedIn", "namePublishedInYear",
    ],
  },
  agent: {
    required: ["agentID"],
    optional: ["agentType", "preferredAgentName", "agentRemarks"],
  },
  "agent-agent-role": {
    required: ["agentID", "relatedAgentID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "agent-identifier": {
    required: ["agentID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "agent-media": {
    required: ["mediaID", "agentID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "bibliographic-resource": {
    required: ["referenceID"],
    optional: [
      "parentReferenceID", "referenceType", "bibliographicCitation",
      "title", "author", "authorID", "editor", "editorID",
      "publisher", "publisherID",
      "volume", "issue", "edition", "pages", "version",
      "issued", "accessed", "peerReviewStatus", "referenceRemarks",
    ],
  },
  "chronometric-age": {
    required: ["chronometricAgeID"],
    optional: [
      "eventID", "verbatimChronometricAge",
      "chronometricAgeProtocol", "chronometricAgeProtocolID",
      "uncalibratedChronometricAge",
      "chronometricAgeConversionProtocol", "chronometricAgeConversionProtocolID",
      "earliestChronometricAge", "earliestChronometricAgeReferenceSystem",
      "latestChronometricAge", "latestChronometricAgeReferenceSystem",
      "chronometricAgeUncertaintyInYears", "chronometricAgeUncertaintyMethod",
      "materialDated", "materialDatedID", "materialDatedRelationship",
      "chronometricAgeDeterminedBy", "chronometricAgeDeterminedByID",
      "chronometricAgeDeterminedDate",
      "chronometricAgeReferences", "chronometricAgeRemarks",
    ],
  },
  "chronometric-age-agent-role": {
    required: ["agentID", "chronometricAgeID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "chronometric-age-assertion": {
    required: ["chronometricAgeID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "chronometric-age-media": {
    required: ["mediaID", "chronometricAgeID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "chronometric-age-protocol": {
    required: ["chronometricAgeID", "protocolID"],
    optional: [],
  },
  "chronometric-age-reference": {
    required: ["chronometricAgeID", "referenceID"],
    optional: ["relationshipType"],
  },
  "geological-context": {
    required: ["geologicalContextID"],
    optional: [
      "earliestEonOrLowestEonothem", "latestEonOrHighestEonothem",
      "earliestEraOrLowestErathem", "latestEraOrHighestErathem",
      "earliestPeriodOrLowestSystem", "latestPeriodOrHighestSystem",
      "earliestEpochOrLowestSeries", "latestEpochOrHighestSeries",
      "earliestAgeOrLowestStage", "latestAgeOrHighestStage",
      "lowestBiostratigraphicZone", "highestBiostratigraphicZone",
      "lithostratigraphicTerms", "lithostratigraphicGroup",
      "formation", "member", "bed",
    ],
  },
  "geological-context-media": {
    required: ["mediaID", "geologicalContextID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "event-agent-role": {
    required: ["agentID", "eventID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "event-assertion": {
    required: ["eventID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "event-identifier": {
    required: ["eventID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "event-media": {
    required: ["mediaID", "eventID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "event-protocol": {
    required: ["eventID", "protocolID"],
    optional: [],
  },
  "event-provenance": {
    required: ["provenanceID", "eventID"],
    optional: [],
  },
  "event-reference": {
    required: ["eventID", "referenceID"],
    optional: ["relationshipType"],
  },
  "molecular-protocol": {
    required: ["molecularProtocolID"],
    optional: [
      "assayType", "samp_name", "project_name", "experimental_factor",
      "samp_taxon_id", "neg_cont_type", "pos_cont_type",
      "env_broad_scale", "env_local_scale", "env_medium",
      "subspecf_gen_lin", "ploidy", "num_replicons", "extrachrom_elements",
      "estimated_size", "ref_biomaterial", "source_mat_id",
      "pathogenicity", "biotic_relationship", "specific_host",
      "host_spec_range", "host_disease_stat", "trophic_level",
      "propagation", "encoded_traits", "rel_to_oxygen",
      "isol_growth_condt", "samp_collec_device", "samp_collec_method",
      "samp_mat_process", "size_frac", "samp_size", "samp_vol_we_dna_ext",
      "source_uvig", "virus_enrich_appr",
      "nucl_acid_ext", "nucl_acid_amp",
      "lib_size", "lib_reads_seqd", "lib_layout", "lib_vector", "lib_screen",
      "target_gene", "target_subfragment",
      "pcr_primers", "mid", "adapters", "pcr_cond",
      "seq_meth", "seq_quality_check", "chimera_check",
      "tax_ident", "assembly_qual", "assembly_name", "assembly_software",
      "annot", "number_contig", "feat_pred", "ref_db",
      "sim_search_meth", "tax_class",
      "_16s_recover", "_16s_recover_software",
      "trnas", "trna_ext_software",
      "compl_score", "compl_software", "compl_appr",
      "contam_score", "contam_screen_input", "contam_screen_param", "decontam_software",
      "sort_tech", "single_cell_lysis_appr", "single_cell_lysis_prot",
      "wga_amp_appr", "wga_amp_kit",
      "bin_param", "bin_software", "reassembly_bin", "mag_cov_software",
      "vir_ident_software", "pred_genome_type", "pred_genome_struc", "detec_type",
      "otu_class_appr", "otu_seq_comp_appr", "otu_db",
      "host_pred_appr", "host_pred_est_acc",
      "associated_resource", "sop",
      "pcr_primer_forward", "pcr_primer_reverse",
      "pcr_primer_name_forward", "pcr_primer_name_reverse", "pcr_primer_reference",
      "DNA_sequence",
      "concentration", "concentrationUnit", "methodDeterminationConcentrationAndRatios",
      "ratioOfAbsorbance260_230", "ratioOfAbsorbance260_280",
      "annealingTemp", "annealingTempUnit",
      "probeReporter", "probeQuencher", "ampliconSize",
      "thresholdQuantificationCycle", "baselineValue", "quantificationCycle",
      "automaticThresholdQuantificationCycle", "automaticBaselineValue",
      "contaminationAssessment",
      "partitionVolume", "partitionVolumeUnit",
      "estimatedNumberOfCopies",
      "amplificationReactionVolume", "amplificationReactionVolumeUnit",
      "pcr_analysis_software", "experimentalVariance",
      "pcr_primer_lod", "pcr_primer_loq",
    ],
  },
  "molecular-protocol-agent-role": {
    required: ["agentID", "molecularProtocolID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "molecular-protocol-assertion": {
    required: ["molecularProtocolID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "molecular-protocol-reference": {
    required: ["referenceID", "molecularProtocolID"],
    optional: ["relationshipType"],
  },
  "nucleotide-analysis": {
    required: ["nucleotideAnalysisID", "eventID", "molecularProtocolID", "nucleotideSequenceID"],
    optional: ["materialEntityID", "readCount", "totalReadCount"],
  },
  "nucleotide-analysis-assertion": {
    required: ["nucleotideAnalysisID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "organism-interaction-media": {
    required: ["mediaID", "organismInteractionID"],
    optional: [
      "subjectCategory", "subjectCategoryIRI", "subjectCategorySource",
      "subjectPartLiteral", "subjectPart",
      "subjectOrientationLiteral", "subjectOrientation",
      "physicalSetting",
    ],
  },
  "organism-interaction-reference": {
    required: ["organismInteractionID", "referenceID"],
    optional: ["relationshipType"],
  },
  "organism-reference": {
    required: ["organismID", "referenceID"],
    optional: ["relationshipType"],
  },
  "organism-relationship": {
    required: ["organismRelationshipID", "subjectOrganismID"],
    optional: [
      "relationshipType", "relationshipTypeIRI", "relationshipTypeSource",
      "relatedOrganismID",
      "externalRelatedOrganismID", "externalRelatedOrganismSource",
      "relationshipOrder",
      "relationshipAccordingTo", "relationshipAccordingToID",
      "relationshipEstablishedDate", "relationshipRemarks",
    ],
  },
  protocol: {
    required: ["protocolID"],
    optional: ["protocolType", "protocolName", "protocolDescription", "protocolReferences", "protocolRemarks"],
  },
  "protocol-reference": {
    required: ["protocolID", "referenceID"],
    optional: ["relationshipType"],
  },
  provenance: {
    required: ["provenanceID"],
    optional: [
      "datasetID", "fundingAttribution", "fundingAttributionID",
      "source", "sourceIRI",
      "creatorLiteral", "creatorID",
      "providerLiteral", "providerID",
      "metadataCreatorLiteral", "metadataCreatorID",
      "metadataProviderLiteral", "metadataProviderID",
      "furtherInformationURL", "feedbackURL",
      "references", "bibliographicCitation",
      "projectID", "projectTitle",
    ],
  },
  "resource-relationship": {
    required: ["resourceRelationshipID", "subjectResourceID"],
    optional: [
      "subjectResourceType", "subjectResourceTypeIRI", "subjectResourceTypeSource",
      "relationshipType", "relationshipTypeIRI", "relationshipTypeSource",
      "relatedResourceID",
      "externalRelatedResourceID", "externalRelatedResourceSource",
      "relatedResourceType", "relatedResourceTypeIRI", "relatedResourceTypeSource",
      "relationshipOrder",
      "relationshipAccordingTo", "relationshipAccordingToID",
      "relationshipEstablishedDate", "relationshipRemarks",
    ],
  },
  survey: {
    required: ["surveyID", "eventID"],
    optional: [
      "siteCount", "siteNestingDescription",
      "verbatimSiteDescriptions", "verbatimSiteNames",
      "geospatialScopeAreaValue", "geospatialScopeAreaUnit",
      "totalAreaSampledValue", "totalAreaSampledUnit",
      "reportedExtremeConditions", "reportedWeather",
      "eventDurationValue", "eventDurationUnit",
      "taxonCompletenessReported", "taxonCompletenessProtocols",
      "isAbsenceReported", "absentTaxa",
      "hasNonTargetTaxa", "nonTargetTaxa", "areNonTargetTaxaFullyReported",
      "hasNonTargetOrganisms",
      "verbatimTargetScope",
      "identifiedBy", "identifiedByID", "identificationReferences",
      "compilationTypes", "compilationSourceTypes",
      "inventoryTypes",
      "protocolNames", "protocolDescriptions", "protocolReferences",
      "isAbundanceReported", "isAbundanceCapReported", "abundanceCap",
      "isVegetationCoverReported",
      "isLeastSpecificTargetCategoryQuantityInclusive",
      "hasVouchers", "voucherInstitutions",
      "hasMaterialSamples", "materialSampleTypes",
      "sampleSizeValue", "sampleSizeUnit",
      "samplingPerformedBy", "samplingPerformedByID",
      "isSamplingEffortReported",
      "samplingEffortProtocol", "samplingEffortProtocolID",
      "samplingEffortValue", "samplingEffortUnit",
      "informationWithheld", "dataGeneralizations",
      "feedbackURL",
    ],
  },
  "survey-agent-role": {
    required: ["agentID", "surveyID"],
    optional: ["agentRole", "agentRoleIRI", "agentRoleSource", "agentRoleOrder", "agentRoleDate"],
  },
  "survey-assertion": {
    required: ["surveyID"],
    optional: [
      "assertionID", "verbatimAssertionType",
      "assertionType", "assertionTypeIRI", "assertionTypeSource",
      "assertionMadeDate", "assertionEffectiveDate",
      "assertionValue", "assertionValueIRI", "assertionValueSource",
      "assertionValueNumeric",
      "assertionUnit", "assertionUnitIRI", "assertionUnitSource",
      "assertionError",
      "assertionBy", "assertionByID",
      "assertionProtocols", "assertionProtocolID",
      "assertionReferences", "assertionRemarks",
    ],
  },
  "survey-identifier": {
    required: ["surveyID", "identifier"],
    optional: ["identifierType", "identifierTypeIRI", "identifierTypeSource", "identifierLanguage"],
  },
  "survey-protocol": {
    required: ["protocolID", "surveyID"],
    optional: [],
  },
  "survey-reference": {
    required: ["referenceID", "surveyID"],
    optional: ["relationshipType"],
  },
  "survey-target": {
    required: ["surveyTargetID", "surveyID", "includeOrExclude", "isSurveyTargetFullyReported"],
    optional: [
      "surveyTargetType", "surveyTargetTypeIRI", "surveyTargetTypeSource",
      "surveyTargetValue", "surveyTargetValueIRI", "surveyTargetValueSource",
      "surveyTargetUnit", "surveyTargetUnitIRI", "surveyTargetUnitSource",
    ],
  },
  "usage-policy": {
    required: ["usagePolicyID"],
    optional: [
      "rights", "rightsIRI", "rightsHolder", "rightsHolderID",
      "owner", "ownerID",
      "usageTerms", "webStatement",
      "accessRights", "license", "licenseLogoURL",
      "licensingException", "credit",
      "attributionLogoURL", "attributionLinkURL",
    ],
  },
};
